[uuid(07AED264-5EF9-4791-B54C-60A2200FC0C2)]
library LFlexASIO
{
	[object, uuid(3CBA3AD0-C819-4171-954D-79025926C5DC)]
	interface IFlexASIO : IUnknown
	{
	};

	[uuid(269CCFE0-1468-4D79-BB1A-2EA19C7B9A95)]
	coclass CFlexASIO
	{
		[default] interface IFlexASIO;
	};
}
