[uuid(42DCBA0A-BA58-4BA7-918F-D34A121F9E8D)]
library LFlexASIO
{
	[object, uuid(40FAA6D2-9235-47C7-BBF0-472BE9AD1ECD)]
	interface IFlexASIO : IUnknown
	{
	};

	[uuid(EE8F66BC-9646-4487-ACB9-0F1C7D68D1FA)]
	coclass CFlexASIO
	{
		[default] interface IFlexASIO;
	};
}
