[uuid(6D0F028A-A8F2-46B6-8BE5-4C8863EC60CB)]
library LFlexASIO
{
	[object, uuid(B98D89E3-BB7C-40BD-9FF7-84FDC39B12CC)]
	interface IFlexASIO : IUnknown
	{
	};

	[uuid(481A01F8-8C63-4573-9163-BB06B0601E60)]
	coclass CFlexASIO
	{
		[default] interface IFlexASIO;
	};
}
